package com.monocept.springautogeneratedemailapp;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class SpringAutogeneratedEmailAppApplicationTests {

	@Test
	void contextLoads() {
	}

}
