
—
gsrc/test/java/com/monocept/springautogeneratedemailapp/SpringAutogeneratedEmailAppApplicationTests.java,d\5\d56dba96aa7e51c36a36b5aa17a544c24a03e45b
’
bsrc/main/java/com/monocept/springautogeneratedemailapp/SpringAutogeneratedEmailAppApplication.java,9\3\9342b0734f6f4759bee1aae89fabc6379203ceb0
Y
)src/main/resources/application.properties,0\6\06f65155ec73600b9fc5c4dc2883d4bb84d8e284
e
5src/main/java/com/monocept/model/ApplicationTest.java,7\5\7556ad166ea3b17cd485b8029129ddfd3bd97ad4
7
pom.xml,4\4\442292b8a7efeabbe4cc176709b833b1792140ec