package com.monocept.springautogeneratedemailapp;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Scope;

@SpringBootApplication
public class SpringAutogeneratedEmailAppApplication {

	public static void main(String[] args) {
		SpringApplication.run(SpringAutogeneratedEmailAppApplication.class, args);
	}

}
